### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by IvyGongoogle** [typefo/freeswitch-sound-cn#1]
您好，怎么使用呢。麻烦给个使用说明吧。
谢谢~

**Comment by typefo** [comment]
将此 freeswitch-sound-cn 目录下所有文件复制到 FreeSWITCH 安装目录下的 sounds 下覆盖即可

**Comment by IvyGongoogle** [comment]
@typefo 谢谢您的回复。我试试。
